### ISSUE TITLE
BAR EFFECT BUG, BAR widths incorrect

### ISSUE THREAD

**Issue by keebler125** [smeighan/nutcracker#16]
when creating a BAR EFFECT.
if only using 4 bars
there is 3 lines of trailing color from the 5th and 6th pallet 

also in BAR EFFECT
expand an collapse result is the same

**Comment by smeighan** [comment]
Please always give your login name (keebler, i figured it out) and the effect name you are referring to.
You have 7 bar effects, but only one has 4 bars so i assume effect name is BARS_4_UP_5_MUL2

I changed the 5th color to pink to verify and it is indeed a bug. You have 4 bars, we should only use 4 colors from your palette.

Thanks for finding the bug i will fix it this week.

sean

**Comment by smeighan** [comment]
Calculation of pixels for each bar woith could be off by if the number pf pxels divided into the total pixels in a strand had a remainder. 

fixed.
