### ISSUE TITLE
BAR EFFECT 2 BUG, direction field is case sensitive

### ISSUE THREAD

**Issue by keebler125** [smeighan/nutcracker#17]
creating a BAR EFFECT
the system constantly freezes
errors
Notice: Undefined variable: pixel_ratio in /users/meighan.net/htdocs/nutcracker/effects/bars.php on line 194

Notice: Undefined variable: n in /users/meighan.net/htdocs/nutcracker/effects/bars.php on line 200

Notice: Undefined variable: n in /users/meighan.net/htdocs/nutcracker/effects/bars.php on line 200

using the 6 bar and still getting same error

**Comment by keebler125** [comment]
please remove this bug.
the problem was i entered DOWN instead of down

perhaps make this NOT case senstive

**Comment by smeighan** [comment]
i would consider case sensitivity a bug, so i will leave this open until i make changes so the field is insensitive to case.

thanks

**Comment by smeighan** [comment]
Now downshift direction field. UP/up both work now.
