### ISSUE TITLE
Create an import / export process for users nutcracker data

### ISSUE THREAD

**Issue by smeighan** [smeighan/nutcracker#18]
build  way for users to export their data to external files. This will allow a safe upgrade when installing code on their local machine

**Comment by kgustafson** [comment]
Sean,  

are you thinking of an XML export/import function?  This seems the way to go to me (cleaner and safer than something like a comma delimited file or other text functions).  If so, I would love to work on this.

Kurt

**Comment by smeighan** [comment]
i had an xml parser, i was just going to create the sql as csv.

if you want to make an xml export and import that would be great.

Please install nutcracker on your local machine.

1) install XAMPP or WAMP
2) install gnuplot (from gnuplot.info). Be sure to have installation 
modify the path variable
3) clone a github of nutcracker and store it into

c:/xampp/htdocs/nutcracker
or
c:/wamp/www/nutcracker

start up xampp/wamp

go to localhost/nutcracker/install.php and when you run it:
1) database nutcracker will be created
2) user nc_user will be created and given rights to nutcracker
3) All data from meighan.net/nutcracker will be loaded.

<--- Installation is now complete -->

go to
localhost/nutcracker and login with your normal login/password
now you can edit locally

go into myphpadmin and look at the tables.

we want exports of
select \* from effects_user_hdr where username='$username';
select \* from effects_user_dtl where username='$username';
select \* from models where username='$username';
select \* from music_object_hdr where username='$username';
select \* from music_object_dtl where music_object_id in (select 
music_object_id from music_object_hdr
  where username='$username');

if this were one xml file (i suggest something like 
export.YYYYMMDDHHMI), then the import would load back just the users 
data. This would allow a complete deletion and re-install if needed and 
they wouldnt lose any changes they had made locally.

thanks for offering.

sean

**Comment by kgustafson** [comment]
Sean,

I installed Nutcracker locally this AM.  I figured out how to install it (looking at the scripts that didn't work 100%) and was able to get it up and running without issue.  Thanks,

Kurt

**Comment by Materdaddy** [comment]
What didn't work?  Was it just the missing SQL files?

**Comment by kgustafson** [comment]
Mater, I think so.  Once I ran the sql installs most of these went away.  I am getting some funny behaviors outside of the stuff I am concentrating on (I am working on the XML out and XML load procedures at the moment).
