### ISSUE TITLE
Matrix Targets Broken

### ISSUE THREAD

**Issue by Materdaddy** [smeighan/nutcracker#20]
When attempting to use a 2D matrix target, gnuplot gives errors:

"workspaces/10/ROOF+TESTFLY.gp", line 28: Can't plot with an empty x range!

I have tested this on "color wash" and "butterfly".

Local install gives this error, hosted version times out and gives a 500 server error (likely from the number of pixels in my test target).

**Comment by smeighan** [comment]
I dont see the effect TESTFLY under the username materdaddy. If you create effects on a local machine be sure to also create those effects on meighan.net/nutcracker so i can test.

i created a bars, worked fine
http://meighan.net/nutcracker/effects/workspaces/10/TEST+BARS_SEAN.gif

Remember that i have not released the horizontal matrix, it is still being worked, the same with a single strand target. Neither of these are functional. I will go and tag these two targets to make sure this is clear.

Only horizontal matrix and megatree should be used.

**Comment by Materdaddy** [comment]
Sorry, I'm not sure which I tried on meighan.net/nutcracker and which were local right now.  I cleaned up a couple since I was re-using the names.  I just tried color wash and it worked this time.  I need to see if I used different parameters last night if you haven't changed anything.

You should be able to see a couple 500s in your apache logs last night that I received, but I'll do more testing to see if I can reproduce the problem.  I used "Grid Matrix" type, not "Horizontal Matrix".

**Comment by smeighan** [comment]
ok, there are some gnuplot errors that are actually warning. if you say 
to plot a data file where there is no data, you get all these extraneous 
stuff. i do consider those something to clean up but they dont effect 
the final image or sequence so i have not prioritized them high yet.

this would be one big problem in releasing local installs, i would no 
longer be able to login as the user and test their issue.
this is why ideally local changes get updated in central database also.
that cause issues , though, if they dont have internet connectivity.

**Comment by smeighan** [comment]
vertical matrix is now fixed.
