### ISSUE TITLE
using Matrix pattern...text is reversed...it looks like I'm looking thru the back of the matrix

### ISSUE THREAD

**Issue by soccershot** [smeighan/nutcracker#29]

**Comment by smeighan** [comment]
have you tried to import sequence into your sequencer? I believe this issue is only with my animated gif preview. I agree it is still a bug, the previews are supposed to match your tree.

but as long as the text works correctly on your device i would rate this as a priority 2 bug.

**Comment by soccershot** [comment]
Sean
I'll give it try tonight.
Thanks
John

**Comment by soccershot** [comment]
Sean
I can't login...user name appears to be ok but the password is not working.
Can you reset my password?
John
