### ISSUE TITLE
Matrix Bug Red

### ISSUE THREAD

**Issue by bekanich** [smeighan/nutcracker#34]
User name bekanich
Using Sleigh5 Met_test

Receive a similar error on all Matrix sequences.  It also seems to generate only the first 39 pixels.

splot '../effects/workspaces/582/SLEIGH5~Met_Test_d_1.dat' using 4:5:6:7 with points lc rgb variable pointtype 7 pointsize 0.6 notitle ^ "/users/meighan.net/htdocs/nutcracker/effects/workspaces/582/SLEIGH5~Met_Test.gp", line 28: Can't plot with an empty x range! 

Purging /users/meighan.net/htdocs/nutcracker/effects/workspaces/582/SLEIGH5~Met_Test_d_1.dat

Purging /users/meighan.net/htdocs/nutcracker/effects/workspaces/582/SLEIGH5~Met_Test_d_2.dat

Purging /users/meighan.net/htdocs/nutcracker/effects/workspaces/582/SLEIGH5~Met_Test_d_3.dat

Purging /users/meighan.net/htdocs/nutcracker/effects/workspaces/582/SLEIGH5~Met_Test_d_4.dat

Purging /users/meighan.net/htdocs/nutcracker/effects/workspaces/582/SLEIGH5~Met_Test_d_5.dat
.......

**Comment by smeighan** [comment]
Fixed vertical matrix target generation.

code ha sbeen released
