### ISSUE TITLE
Possible Bug in Single Strand Output

### ISSUE THREAD

**Issue by bajadahl** [smeighan/nutcracker#36]
Created a small single strand with 3 segments effect with one string of 50 pixels.  Color 1: Blue  1 pixel, Color 2 white 5 pixels.  10 second effect.  About halfway through the effect 5 pixels of blue traverse all three segments.  The effect does output the artifact to the UserPatterns file for LSP.

User: bajadahl
Effect: SS_Tutor12

**Comment by smeighan** [comment]
color artifcat fixed with latest code release 9-21-12

one other note, you might have the speed in your effects too high. i think normal speeds are 0.5 to 2

thanks
