### ISSUE TITLE
text only shows up as 1/4 tree instead of 1/2 tree

### ISSUE THREAD

**Issue by jnealand** [smeighan/nutcracker#41]
I created a simple two line Merry Christmas test message.  On the gif it only shows up on the left half of my half tree.  On my actual tree it is the same, I only get text on the left half of my half tree..

**Comment by jnealand** [comment]
Went back and tried this as a 360 tree.  Still does not work

**Comment by jnealand** [comment]
I went back and defined a full 360 tree and was able to get my Merry Christmas to display.  I did not have the full tree specified correctly on my first try.  Still it seems like it should work on the half tree.

**Comment by smeighan** [comment]
released new text effect that now fills the tree correctly.

**Comment by jnealand** [comment]
I tested this and it works great.
