### ISSUE TITLE
Incorrect links on page admin.php under local install

### ISSUE THREAD

**Issue by injury99** [smeighan/nutcracker#44]
some issues with the links on admin.php using the local install.

on the admin.php page itself the links for cleanup and submit a bug point to the /effects/ directory which does not have the appropriate targets (they are in the /admin/ directory). 

On the navigation bar hover Clean Up and Submit a Bug are correctly pointing to the /admin/ directory

The tutorials link in both places (hover menu and table on admin.php) point to /effects/tutorials.html which does not exist (it to is in admin) but as the flash files aren't downloaded it probably doesn't matter. 

Cannot reproduce this problem in the online version.

**Comment by kgustafson** [comment]
Fixed errors on admin.php.
