### ISSUE TITLE
Project Output ... was working, but no more [Vixen 2.1]

### ISSUE THREAD

**Issue by hicksjo** [smeighan/nutcracker#50]
I am using .net site and have created project, it appears to be working to create a Vixen 2.1 output file, but I never get a link to the file to download or save ... below is bottom portion of text that appears on screen after choosing OUTPUT FILE

username:  hicksjfh
project:  Christmas Must Be Something More
model:  TREE288

appreciate any help ... I know I can output the individual effects and load those, but got really spoiled already with the one project i successfully created earlier this week

Erasing gaps and joining effects

Intro   R_GAR_SPARKLE   Adding 354 of effect R_GAR_SPARKLE from frame 0 to frame 353
Verse1  R_TWINKLE   Adding 442 of effect R_TWINKLE from frame 354 to frame 795
chorus1 B_GLITTER_FAST  Adding 632 of effect B_GLITTER_FAST from frame 796 to frame 1427
chorus1b    B_TO_BLK_BARS_UP_MED    Adding 238 of effect B_TO_BLK_BARS_UP_MED from frame 1428 to frame 1665
verse2  SPIRALBLUE-WHITE    Adding 461 of effect SPIRALBLUE-WHITE from frame 1666 to frame 2126
chorus2 B_TO_BLK_BARS_DWN_MED   Adding 625 of effect B_TO_BLK_BARS_DWN_MED from frame 2127 to frame 2751 ... etc.

Writing to workarea/hicksjfh~133~master.nc

Creating VIR file from master

Generating Event String for Vixen from VIR file

**Comment by kgustafson** [comment]
I am able to recreate your issue on meighan.net.  Will test on local copy to see if it is a site specific issue.

Kurt

**Comment by hicksjo** [comment]
Thank you

Going to save me a lot of time if you get it working again

Still very appreciative of the work you guys have put into this either way

Josh

**Comment by hicksjo** [comment]
Kurt - FYI,
I was able to find the file that was created (hicksjfh~133.vir) and download it from the work area but still no link appearing

Josh

**Comment by kgustafson** [comment]
Is this still an issue?  I think we fixed this.

**Comment by hicksjo** [comment]
It's been working for me on new server ... Suspect my projects were just taking too long

Thanks
