### ISSUE TITLE
error accessing projects page

### ISSUE THREAD

**Issue by hicksjo** [smeighan/nutcracker#53]
getting the following error after clicking "Manage Projects" tab

Fatal error: Cannot redeclare create_twinkle() (previously declared in /users/meighan.net/htdocs/nutcracker/effects/f_twinkle.php:193) in /users/meighan.net/htdocs/nutcracker/effects/read_file.php on line 2684

**Comment by kgustafson** [comment]
This was fixed in an earlier release
