### ISSUE TITLE
Request-URI Too Large

### ISSUE THREAD

**Issue by zoobmarine** [smeighan/nutcracker#57]
On second page of Single Strand with a 70 pixels I get the following error

Request-URI Too Large
The requested URL's length exceeds the capacity limit for this server.

Is using get instead of post and Request URI is more than 255 limit

**Comment by smeighan** [comment]
i have never seen thsi error.

what user name, target and effect where you using?

thanks

**Comment by zoobmarine** [comment]
username: zoobmarine
target: SINGLE
effect: single strand

In second page, where you can choose colors

**Comment by smeighan** [comment]
You single strand model had 70 pixels but you had segments sa zero.

You must divide your pixel pile into segments. To give you an example, i 
set your 70 pixels into 2 segments, 35 nodes each.

here is what that now looks like

http://nutcracker123.com/nutcracker/effects/workspaces/654/SINGLE~SINGLES1.gif

remember, you must have a non zero segment count.

The idea of single strands was take whatever you have, put it all 
toegter into one big mega string. Then divide that huge pile into segments.

**Comment by kgustafson** [comment]
Sean,

we should error check for an entry of segments = 0 (along with a heck of a lot of extra error checks like a blank name for the effect name or target name, etc.)

**Comment by smeighan** [comment]
Yes, i agree. I am going to close this bug. We need a separate bug to track getting input validation.
